version: '3.7'
services:
  org.jediassessments.gateway:
    image: nginx
    container_name: gateway
    extra_hosts:
        - "host.docker.internal:host-gateway"
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        # - ./proxy_params:/etc/nginx/proxy_params
    ports:
        - 80:80

  galacticstandardcalendar:
    image: jediassessments/galacticstandardcalendar
    container_name: galacticstandardcalendar
    ports:
        - 8080:8080
