version: '3.7'
services:
  org.jediassessments.gateway:
    image: nginx
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    # - ./proxy_params:/etc/nginx/proxy_params
    ports:
      - 80:80

  galacticstandardcalendar:
    image: jediassessments/galacticstandardcalendar
    ports:
      - 8080:8080
